services:
    _defaults:
        autowire: true
        autoconfigure: true

    Sentimo\Client\HttpClient\Client:
        public: true
        arguments:
            $httpClient: '@GuzzleHttp\Client'
            $config: '@Sentimo\Client\Config'
            $requestParamBuilder: '@Sentimo\Client\RequestParam\ReviewPostRequestParamBuilder'
            $reviewFactory: '@Sentimo\Client\ReviewFactory'

    GuzzleHttp\Client:
        arguments:
            $config:
                base_uri: '%api.base_uri%'

    Symfony\Component\Cache\Adapter\FilesystemAdapter: ~

    Sentimo\Client\Config:
        arguments:
            - '%api.key%'

    Sentimo\Client\RequestParam\ReviewPostRequestParamBuilder: ~

    Sentimo\Client\ReviewFactory: ~
